//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOUHOU_T_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOUHOU_T
    {
        public int ID { get; set; }
        public string PATIENTS_NAME { get; set; }
        public string PATIENTS_ADDRESS { get; set; }
        public int GROUP_ID { get; set; }
    
        public virtual GROUP_T GROUP_T { get; set; }
    }
}
